version: "3"

services:
  server:
    build:
      context: ./nodejs
    depends_on:
      - db
    volumes:
      - ./nodejs/app:/app
    ports:
      - "3001:3000"
    command: node /app/index.js
    restart: always

  db:
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: node
      MYSQL_PASSWORD: node
      MYSQL_DATABASE: example
    restart: always

